run:
  timeout: 3m
  skip-dirs:
    - /internal/entities

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - wsl
    - whitespace
    - misspell
    - ireturn
    - gosec
    - gofmt
    - contextcheck
    - dupl
    - goconst
    - gocritic
    - importas
    - nilnil
    - exhaustruct
    - goprintffuncname
    - dogsled
