services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    environment:
      - HOME=/go/src/github.com/scoretrak/scoretrak
    ports:
      - 3001:3001
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: .
      target: /go/src/github.com/scoretrak/scoretrak
    depends_on:
      - cockroachdb

  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    environment:
      - COCKROACH_DATABASE=scoretrak
      - COCKROACH_USER=st_admin
    ports:
      - 26257:26257
      - 8080:8080

  proxy:
    image: envoyproxy/envoy:v1.25.0
    ports:
      - 8000:8000
      - 8000:9901
    depends_on:
      - app
    links:
      - "app:scoretrak"
    volumes:
    - type: bind
      source: ./configs/envoy/config.yaml
      target: /etc/envoy/envoy.yaml
