openapi: 3.0.3
info:
  description: API for scoretrak, competition scoring engine
  title: ScoreTrak
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
security:
  - ApiToken: []
externalDocs:
  description: Find out more about ScoreTrak
  url: http://github.com/scoretrak/scoretrak/tree/main/docs
tags:
  - name: competition
    description: Competitions
paths:
  /v1/competitions:
    $ref: paths/v1_competitions.yaml
  /v1/competitions/{id}:
    $ref: paths/v1_competitions_{id}.yaml
components:
  securitySchemes:
    ApiToken:
      scheme: bearer
      type: http
