serve:
  proxy:
    port: 4455 # run the proxy at port 4455
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:5173
        - http://*.localhost:5173
      allow_credentials: true
  api:
    port: 4456 # run the api at port 4456
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:5173
        - http://*.localhost:5173
      allow_credentials: true

access_rules:
  repositories:
    - file://./config/ory/oathkeeper/rules.json
  matching_strategy: regexp

authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: http://localhost:4433/sessions/whoami
      only:
        - ory_kratos_session
      preserve_path: true
#      forward_http_headers:
#        - Connect
#        - Authorization
#        - Cookie
#        - X-Forwarded-For

#  bearer_token:
#    enabled: true
#    config:
#
  anonymous:
    enabled: true
    config:
      subject: spectator

errors:
  handlers:
    json:
      enabled: true

authorizers:
  allow:
    enabled: true
  keto_engine_acp_ory:
    config:
      base_url: http://localhost:4467/
      flavor: exact


mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"

log:
  leak_sensitive_values: true
