version: "3.8"
services:
  scoretrak:
    image: ghcr.io/scoretrak/scoretrak/scoretrak-server:v0.1.9
    restart: on-failure
    ports:
      - "33333:33333"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/deployments
    depends_on:
      - db-init
    command: ./master -config /deployments/docker-standalone/config.yml

  scoretrak-web:
    image: ghcr.io/scoretrak/client/scoretrak-client:v0.1.7
    depends_on:
      - scoretrak

  cockroachdb-1:
    container_name: cockroachdb-1
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      default:
        aliases:
          - cockroach

  db-init:
    depends_on:
      - cockroachdb-1
    image: cockroachdb/cockroach:latest
    restart: on-failure
    command: sql --execute="CREATE DATABASE IF NOT EXISTS scoretrak; " --insecure --host cockroach

  envoy:
    image: envoyproxy/envoy:v1.16-latest
    volumes:
      - type: bind
        source: ./envoy.yaml
        target: /etc/envoy/envoy.yaml
    depends_on:
      - scoretrak
    ports:
      - "8000:8000"
      - "9901:9901"
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml

networks:
  default:
    attachable: yes


