roundduration: 60

enabled: False

server:
  address: 0.0.0.0
  port: 3001

db:
  cockroach:
    host: localhost
    database: "scoretrak"
    username: root
    password: ""

open-telemetry:
#    endpoint: "http://localhost:14268/api/traces"
#    username: ""
#    password: ""

logger:
  environment: dev
