roundduration: 60

enabled: False

db:
  automigrate: true
  cockroach:
    host: localhost
    database: "scoretrak"
    username: root
    password: ""

open-telemetry:
  jaeger:
#    endpoint: "http://localhost:14268/api/traces"
#    username: ""
#    password: ""

logger:
  environment: dev
