server:
  address: 0.0.0.0
  port: 3001

db:
  use: "postgresql"
  host: "postgresqldb"
  port: "5432"
  database: "scoretrak"
  username: "st_admin"
  password: "password"
  seed: true
  migrate: true

open-telemetry:
#    endpoint: "http://localhost:14268/api/traces"
#    username: ""
#    password: ""

logger:
  environment: dev
