// Code generated by ogen, DO NOT EDIT.

package ogent

// setDefaults set default value of fields.
func (s *CreatePropertyReq) setDefaults() {
	{
		val := CreatePropertyReqStatus("view")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *PropertyCreate) setDefaults() {
	{
		val := PropertyCreateStatus("view")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *PropertyList) setDefaults() {
	{
		val := PropertyListStatus("view")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *PropertyRead) setDefaults() {
	{
		val := PropertyReadStatus("view")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *PropertyUpdate) setDefaults() {
	{
		val := PropertyUpdateStatus("view")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *ServicePropertiesList) setDefaults() {
	{
		val := ServicePropertiesListStatus("view")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *UpdatePropertyReq) setDefaults() {
	{
		val := UpdatePropertyReqStatus("view")
		s.Status.SetTo(val)
	}
}
