// Code generated by ent, DO NOT EDIT.

package entities

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ScoreTrak/ScoreTrak/internal/entities/competition"
	"github.com/ScoreTrak/ScoreTrak/internal/entities/predicate"
	"github.com/ScoreTrak/ScoreTrak/internal/entities/report"
	"github.com/ScoreTrak/ScoreTrak/internal/entities/round"
	"github.com/ScoreTrak/ScoreTrak/internal/entities/service"
	"github.com/ScoreTrak/ScoreTrak/internal/entities/team"
)

// CompetitionUpdate is the builder for updating Competition entities.
type CompetitionUpdate struct {
	config
	hooks    []Hook
	mutation *CompetitionMutation
}

// Where appends a list predicates to the CompetitionUpdate builder.
func (cu *CompetitionUpdate) Where(ps ...predicate.Competition) *CompetitionUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetHidden sets the "hidden" field.
func (cu *CompetitionUpdate) SetHidden(b bool) *CompetitionUpdate {
	cu.mutation.SetHidden(b)
	return cu
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (cu *CompetitionUpdate) SetNillableHidden(b *bool) *CompetitionUpdate {
	if b != nil {
		cu.SetHidden(*b)
	}
	return cu
}

// ClearHidden clears the value of the "hidden" field.
func (cu *CompetitionUpdate) ClearHidden() *CompetitionUpdate {
	cu.mutation.ClearHidden()
	return cu
}

// SetPause sets the "pause" field.
func (cu *CompetitionUpdate) SetPause(b bool) *CompetitionUpdate {
	cu.mutation.SetPause(b)
	return cu
}

// SetNillablePause sets the "pause" field if the given value is not nil.
func (cu *CompetitionUpdate) SetNillablePause(b *bool) *CompetitionUpdate {
	if b != nil {
		cu.SetPause(*b)
	}
	return cu
}

// ClearPause clears the value of the "pause" field.
func (cu *CompetitionUpdate) ClearPause() *CompetitionUpdate {
	cu.mutation.ClearPause()
	return cu
}

// SetName sets the "name" field.
func (cu *CompetitionUpdate) SetName(s string) *CompetitionUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetDisplayName sets the "display_name" field.
func (cu *CompetitionUpdate) SetDisplayName(s string) *CompetitionUpdate {
	cu.mutation.SetDisplayName(s)
	return cu
}

// SetViewableToPublic sets the "viewable_to_public" field.
func (cu *CompetitionUpdate) SetViewableToPublic(b bool) *CompetitionUpdate {
	cu.mutation.SetViewableToPublic(b)
	return cu
}

// SetNillableViewableToPublic sets the "viewable_to_public" field if the given value is not nil.
func (cu *CompetitionUpdate) SetNillableViewableToPublic(b *bool) *CompetitionUpdate {
	if b != nil {
		cu.SetViewableToPublic(*b)
	}
	return cu
}

// ClearViewableToPublic clears the value of the "viewable_to_public" field.
func (cu *CompetitionUpdate) ClearViewableToPublic() *CompetitionUpdate {
	cu.mutation.ClearViewableToPublic()
	return cu
}

// SetToBeStartedAt sets the "to_be_started_at" field.
func (cu *CompetitionUpdate) SetToBeStartedAt(t time.Time) *CompetitionUpdate {
	cu.mutation.SetToBeStartedAt(t)
	return cu
}

// SetNillableToBeStartedAt sets the "to_be_started_at" field if the given value is not nil.
func (cu *CompetitionUpdate) SetNillableToBeStartedAt(t *time.Time) *CompetitionUpdate {
	if t != nil {
		cu.SetToBeStartedAt(*t)
	}
	return cu
}

// ClearToBeStartedAt clears the value of the "to_be_started_at" field.
func (cu *CompetitionUpdate) ClearToBeStartedAt() *CompetitionUpdate {
	cu.mutation.ClearToBeStartedAt()
	return cu
}

// SetStartedAt sets the "started_at" field.
func (cu *CompetitionUpdate) SetStartedAt(t time.Time) *CompetitionUpdate {
	cu.mutation.SetStartedAt(t)
	return cu
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (cu *CompetitionUpdate) SetNillableStartedAt(t *time.Time) *CompetitionUpdate {
	if t != nil {
		cu.SetStartedAt(*t)
	}
	return cu
}

// ClearStartedAt clears the value of the "started_at" field.
func (cu *CompetitionUpdate) ClearStartedAt() *CompetitionUpdate {
	cu.mutation.ClearStartedAt()
	return cu
}

// SetFinishedAt sets the "finished_at" field.
func (cu *CompetitionUpdate) SetFinishedAt(t time.Time) *CompetitionUpdate {
	cu.mutation.SetFinishedAt(t)
	return cu
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (cu *CompetitionUpdate) SetNillableFinishedAt(t *time.Time) *CompetitionUpdate {
	if t != nil {
		cu.SetFinishedAt(*t)
	}
	return cu
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (cu *CompetitionUpdate) ClearFinishedAt() *CompetitionUpdate {
	cu.mutation.ClearFinishedAt()
	return cu
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (cu *CompetitionUpdate) AddTeamIDs(ids ...string) *CompetitionUpdate {
	cu.mutation.AddTeamIDs(ids...)
	return cu
}

// AddTeams adds the "teams" edges to the Team entity.
func (cu *CompetitionUpdate) AddTeams(t ...*Team) *CompetitionUpdate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cu.AddTeamIDs(ids...)
}

// AddServiceIDs adds the "services" edge to the Service entity by IDs.
func (cu *CompetitionUpdate) AddServiceIDs(ids ...string) *CompetitionUpdate {
	cu.mutation.AddServiceIDs(ids...)
	return cu
}

// AddServices adds the "services" edges to the Service entity.
func (cu *CompetitionUpdate) AddServices(s ...*Service) *CompetitionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.AddServiceIDs(ids...)
}

// AddReportIDs adds the "reports" edge to the Report entity by IDs.
func (cu *CompetitionUpdate) AddReportIDs(ids ...int) *CompetitionUpdate {
	cu.mutation.AddReportIDs(ids...)
	return cu
}

// AddReports adds the "reports" edges to the Report entity.
func (cu *CompetitionUpdate) AddReports(r ...*Report) *CompetitionUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.AddReportIDs(ids...)
}

// AddRoundIDs adds the "rounds" edge to the Round entity by IDs.
func (cu *CompetitionUpdate) AddRoundIDs(ids ...string) *CompetitionUpdate {
	cu.mutation.AddRoundIDs(ids...)
	return cu
}

// AddRounds adds the "rounds" edges to the Round entity.
func (cu *CompetitionUpdate) AddRounds(r ...*Round) *CompetitionUpdate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.AddRoundIDs(ids...)
}

// Mutation returns the CompetitionMutation object of the builder.
func (cu *CompetitionUpdate) Mutation() *CompetitionMutation {
	return cu.mutation
}

// ClearTeams clears all "teams" edges to the Team entity.
func (cu *CompetitionUpdate) ClearTeams() *CompetitionUpdate {
	cu.mutation.ClearTeams()
	return cu
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (cu *CompetitionUpdate) RemoveTeamIDs(ids ...string) *CompetitionUpdate {
	cu.mutation.RemoveTeamIDs(ids...)
	return cu
}

// RemoveTeams removes "teams" edges to Team entities.
func (cu *CompetitionUpdate) RemoveTeams(t ...*Team) *CompetitionUpdate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cu.RemoveTeamIDs(ids...)
}

// ClearServices clears all "services" edges to the Service entity.
func (cu *CompetitionUpdate) ClearServices() *CompetitionUpdate {
	cu.mutation.ClearServices()
	return cu
}

// RemoveServiceIDs removes the "services" edge to Service entities by IDs.
func (cu *CompetitionUpdate) RemoveServiceIDs(ids ...string) *CompetitionUpdate {
	cu.mutation.RemoveServiceIDs(ids...)
	return cu
}

// RemoveServices removes "services" edges to Service entities.
func (cu *CompetitionUpdate) RemoveServices(s ...*Service) *CompetitionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.RemoveServiceIDs(ids...)
}

// ClearReports clears all "reports" edges to the Report entity.
func (cu *CompetitionUpdate) ClearReports() *CompetitionUpdate {
	cu.mutation.ClearReports()
	return cu
}

// RemoveReportIDs removes the "reports" edge to Report entities by IDs.
func (cu *CompetitionUpdate) RemoveReportIDs(ids ...int) *CompetitionUpdate {
	cu.mutation.RemoveReportIDs(ids...)
	return cu
}

// RemoveReports removes "reports" edges to Report entities.
func (cu *CompetitionUpdate) RemoveReports(r ...*Report) *CompetitionUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.RemoveReportIDs(ids...)
}

// ClearRounds clears all "rounds" edges to the Round entity.
func (cu *CompetitionUpdate) ClearRounds() *CompetitionUpdate {
	cu.mutation.ClearRounds()
	return cu
}

// RemoveRoundIDs removes the "rounds" edge to Round entities by IDs.
func (cu *CompetitionUpdate) RemoveRoundIDs(ids ...string) *CompetitionUpdate {
	cu.mutation.RemoveRoundIDs(ids...)
	return cu
}

// RemoveRounds removes "rounds" edges to Round entities.
func (cu *CompetitionUpdate) RemoveRounds(r ...*Round) *CompetitionUpdate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.RemoveRoundIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CompetitionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, CompetitionMutation](ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CompetitionUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CompetitionUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CompetitionUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CompetitionUpdate) check() error {
	if v, ok := cu.mutation.Name(); ok {
		if err := competition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entities: validator failed for field "Competition.name": %w`, err)}
		}
	}
	if v, ok := cu.mutation.DisplayName(); ok {
		if err := competition.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`entities: validator failed for field "Competition.display_name": %w`, err)}
		}
	}
	return nil
}

func (cu *CompetitionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(competition.Table, competition.Columns, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeString))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Hidden(); ok {
		_spec.SetField(competition.FieldHidden, field.TypeBool, value)
	}
	if cu.mutation.HiddenCleared() {
		_spec.ClearField(competition.FieldHidden, field.TypeBool)
	}
	if value, ok := cu.mutation.Pause(); ok {
		_spec.SetField(competition.FieldPause, field.TypeBool, value)
	}
	if cu.mutation.PauseCleared() {
		_spec.ClearField(competition.FieldPause, field.TypeBool)
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(competition.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.DisplayName(); ok {
		_spec.SetField(competition.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := cu.mutation.ViewableToPublic(); ok {
		_spec.SetField(competition.FieldViewableToPublic, field.TypeBool, value)
	}
	if cu.mutation.ViewableToPublicCleared() {
		_spec.ClearField(competition.FieldViewableToPublic, field.TypeBool)
	}
	if value, ok := cu.mutation.ToBeStartedAt(); ok {
		_spec.SetField(competition.FieldToBeStartedAt, field.TypeTime, value)
	}
	if cu.mutation.ToBeStartedAtCleared() {
		_spec.ClearField(competition.FieldToBeStartedAt, field.TypeTime)
	}
	if value, ok := cu.mutation.StartedAt(); ok {
		_spec.SetField(competition.FieldStartedAt, field.TypeTime, value)
	}
	if cu.mutation.StartedAtCleared() {
		_spec.ClearField(competition.FieldStartedAt, field.TypeTime)
	}
	if value, ok := cu.mutation.FinishedAt(); ok {
		_spec.SetField(competition.FieldFinishedAt, field.TypeTime, value)
	}
	if cu.mutation.FinishedAtCleared() {
		_spec.ClearField(competition.FieldFinishedAt, field.TypeTime)
	}
	if cu.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.TeamsTable,
			Columns: []string{competition.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !cu.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.TeamsTable,
			Columns: []string{competition.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.TeamsTable,
			Columns: []string{competition.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ServicesTable,
			Columns: []string{competition.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedServicesIDs(); len(nodes) > 0 && !cu.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ServicesTable,
			Columns: []string{competition.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ServicesTable,
			Columns: []string{competition.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ReportsTable,
			Columns: []string{competition.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedReportsIDs(); len(nodes) > 0 && !cu.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ReportsTable,
			Columns: []string{competition.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ReportsTable,
			Columns: []string{competition.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RoundsTable,
			Columns: []string{competition.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedRoundsIDs(); len(nodes) > 0 && !cu.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RoundsTable,
			Columns: []string{competition.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RoundsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RoundsTable,
			Columns: []string{competition.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{competition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CompetitionUpdateOne is the builder for updating a single Competition entity.
type CompetitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompetitionMutation
}

// SetHidden sets the "hidden" field.
func (cuo *CompetitionUpdateOne) SetHidden(b bool) *CompetitionUpdateOne {
	cuo.mutation.SetHidden(b)
	return cuo
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (cuo *CompetitionUpdateOne) SetNillableHidden(b *bool) *CompetitionUpdateOne {
	if b != nil {
		cuo.SetHidden(*b)
	}
	return cuo
}

// ClearHidden clears the value of the "hidden" field.
func (cuo *CompetitionUpdateOne) ClearHidden() *CompetitionUpdateOne {
	cuo.mutation.ClearHidden()
	return cuo
}

// SetPause sets the "pause" field.
func (cuo *CompetitionUpdateOne) SetPause(b bool) *CompetitionUpdateOne {
	cuo.mutation.SetPause(b)
	return cuo
}

// SetNillablePause sets the "pause" field if the given value is not nil.
func (cuo *CompetitionUpdateOne) SetNillablePause(b *bool) *CompetitionUpdateOne {
	if b != nil {
		cuo.SetPause(*b)
	}
	return cuo
}

// ClearPause clears the value of the "pause" field.
func (cuo *CompetitionUpdateOne) ClearPause() *CompetitionUpdateOne {
	cuo.mutation.ClearPause()
	return cuo
}

// SetName sets the "name" field.
func (cuo *CompetitionUpdateOne) SetName(s string) *CompetitionUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetDisplayName sets the "display_name" field.
func (cuo *CompetitionUpdateOne) SetDisplayName(s string) *CompetitionUpdateOne {
	cuo.mutation.SetDisplayName(s)
	return cuo
}

// SetViewableToPublic sets the "viewable_to_public" field.
func (cuo *CompetitionUpdateOne) SetViewableToPublic(b bool) *CompetitionUpdateOne {
	cuo.mutation.SetViewableToPublic(b)
	return cuo
}

// SetNillableViewableToPublic sets the "viewable_to_public" field if the given value is not nil.
func (cuo *CompetitionUpdateOne) SetNillableViewableToPublic(b *bool) *CompetitionUpdateOne {
	if b != nil {
		cuo.SetViewableToPublic(*b)
	}
	return cuo
}

// ClearViewableToPublic clears the value of the "viewable_to_public" field.
func (cuo *CompetitionUpdateOne) ClearViewableToPublic() *CompetitionUpdateOne {
	cuo.mutation.ClearViewableToPublic()
	return cuo
}

// SetToBeStartedAt sets the "to_be_started_at" field.
func (cuo *CompetitionUpdateOne) SetToBeStartedAt(t time.Time) *CompetitionUpdateOne {
	cuo.mutation.SetToBeStartedAt(t)
	return cuo
}

// SetNillableToBeStartedAt sets the "to_be_started_at" field if the given value is not nil.
func (cuo *CompetitionUpdateOne) SetNillableToBeStartedAt(t *time.Time) *CompetitionUpdateOne {
	if t != nil {
		cuo.SetToBeStartedAt(*t)
	}
	return cuo
}

// ClearToBeStartedAt clears the value of the "to_be_started_at" field.
func (cuo *CompetitionUpdateOne) ClearToBeStartedAt() *CompetitionUpdateOne {
	cuo.mutation.ClearToBeStartedAt()
	return cuo
}

// SetStartedAt sets the "started_at" field.
func (cuo *CompetitionUpdateOne) SetStartedAt(t time.Time) *CompetitionUpdateOne {
	cuo.mutation.SetStartedAt(t)
	return cuo
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (cuo *CompetitionUpdateOne) SetNillableStartedAt(t *time.Time) *CompetitionUpdateOne {
	if t != nil {
		cuo.SetStartedAt(*t)
	}
	return cuo
}

// ClearStartedAt clears the value of the "started_at" field.
func (cuo *CompetitionUpdateOne) ClearStartedAt() *CompetitionUpdateOne {
	cuo.mutation.ClearStartedAt()
	return cuo
}

// SetFinishedAt sets the "finished_at" field.
func (cuo *CompetitionUpdateOne) SetFinishedAt(t time.Time) *CompetitionUpdateOne {
	cuo.mutation.SetFinishedAt(t)
	return cuo
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (cuo *CompetitionUpdateOne) SetNillableFinishedAt(t *time.Time) *CompetitionUpdateOne {
	if t != nil {
		cuo.SetFinishedAt(*t)
	}
	return cuo
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (cuo *CompetitionUpdateOne) ClearFinishedAt() *CompetitionUpdateOne {
	cuo.mutation.ClearFinishedAt()
	return cuo
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (cuo *CompetitionUpdateOne) AddTeamIDs(ids ...string) *CompetitionUpdateOne {
	cuo.mutation.AddTeamIDs(ids...)
	return cuo
}

// AddTeams adds the "teams" edges to the Team entity.
func (cuo *CompetitionUpdateOne) AddTeams(t ...*Team) *CompetitionUpdateOne {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cuo.AddTeamIDs(ids...)
}

// AddServiceIDs adds the "services" edge to the Service entity by IDs.
func (cuo *CompetitionUpdateOne) AddServiceIDs(ids ...string) *CompetitionUpdateOne {
	cuo.mutation.AddServiceIDs(ids...)
	return cuo
}

// AddServices adds the "services" edges to the Service entity.
func (cuo *CompetitionUpdateOne) AddServices(s ...*Service) *CompetitionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.AddServiceIDs(ids...)
}

// AddReportIDs adds the "reports" edge to the Report entity by IDs.
func (cuo *CompetitionUpdateOne) AddReportIDs(ids ...int) *CompetitionUpdateOne {
	cuo.mutation.AddReportIDs(ids...)
	return cuo
}

// AddReports adds the "reports" edges to the Report entity.
func (cuo *CompetitionUpdateOne) AddReports(r ...*Report) *CompetitionUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.AddReportIDs(ids...)
}

// AddRoundIDs adds the "rounds" edge to the Round entity by IDs.
func (cuo *CompetitionUpdateOne) AddRoundIDs(ids ...string) *CompetitionUpdateOne {
	cuo.mutation.AddRoundIDs(ids...)
	return cuo
}

// AddRounds adds the "rounds" edges to the Round entity.
func (cuo *CompetitionUpdateOne) AddRounds(r ...*Round) *CompetitionUpdateOne {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.AddRoundIDs(ids...)
}

// Mutation returns the CompetitionMutation object of the builder.
func (cuo *CompetitionUpdateOne) Mutation() *CompetitionMutation {
	return cuo.mutation
}

// ClearTeams clears all "teams" edges to the Team entity.
func (cuo *CompetitionUpdateOne) ClearTeams() *CompetitionUpdateOne {
	cuo.mutation.ClearTeams()
	return cuo
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (cuo *CompetitionUpdateOne) RemoveTeamIDs(ids ...string) *CompetitionUpdateOne {
	cuo.mutation.RemoveTeamIDs(ids...)
	return cuo
}

// RemoveTeams removes "teams" edges to Team entities.
func (cuo *CompetitionUpdateOne) RemoveTeams(t ...*Team) *CompetitionUpdateOne {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cuo.RemoveTeamIDs(ids...)
}

// ClearServices clears all "services" edges to the Service entity.
func (cuo *CompetitionUpdateOne) ClearServices() *CompetitionUpdateOne {
	cuo.mutation.ClearServices()
	return cuo
}

// RemoveServiceIDs removes the "services" edge to Service entities by IDs.
func (cuo *CompetitionUpdateOne) RemoveServiceIDs(ids ...string) *CompetitionUpdateOne {
	cuo.mutation.RemoveServiceIDs(ids...)
	return cuo
}

// RemoveServices removes "services" edges to Service entities.
func (cuo *CompetitionUpdateOne) RemoveServices(s ...*Service) *CompetitionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.RemoveServiceIDs(ids...)
}

// ClearReports clears all "reports" edges to the Report entity.
func (cuo *CompetitionUpdateOne) ClearReports() *CompetitionUpdateOne {
	cuo.mutation.ClearReports()
	return cuo
}

// RemoveReportIDs removes the "reports" edge to Report entities by IDs.
func (cuo *CompetitionUpdateOne) RemoveReportIDs(ids ...int) *CompetitionUpdateOne {
	cuo.mutation.RemoveReportIDs(ids...)
	return cuo
}

// RemoveReports removes "reports" edges to Report entities.
func (cuo *CompetitionUpdateOne) RemoveReports(r ...*Report) *CompetitionUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.RemoveReportIDs(ids...)
}

// ClearRounds clears all "rounds" edges to the Round entity.
func (cuo *CompetitionUpdateOne) ClearRounds() *CompetitionUpdateOne {
	cuo.mutation.ClearRounds()
	return cuo
}

// RemoveRoundIDs removes the "rounds" edge to Round entities by IDs.
func (cuo *CompetitionUpdateOne) RemoveRoundIDs(ids ...string) *CompetitionUpdateOne {
	cuo.mutation.RemoveRoundIDs(ids...)
	return cuo
}

// RemoveRounds removes "rounds" edges to Round entities.
func (cuo *CompetitionUpdateOne) RemoveRounds(r ...*Round) *CompetitionUpdateOne {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.RemoveRoundIDs(ids...)
}

// Where appends a list predicates to the CompetitionUpdate builder.
func (cuo *CompetitionUpdateOne) Where(ps ...predicate.Competition) *CompetitionUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CompetitionUpdateOne) Select(field string, fields ...string) *CompetitionUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Competition entity.
func (cuo *CompetitionUpdateOne) Save(ctx context.Context) (*Competition, error) {
	return withHooks[*Competition, CompetitionMutation](ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CompetitionUpdateOne) SaveX(ctx context.Context) *Competition {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CompetitionUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CompetitionUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CompetitionUpdateOne) check() error {
	if v, ok := cuo.mutation.Name(); ok {
		if err := competition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entities: validator failed for field "Competition.name": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.DisplayName(); ok {
		if err := competition.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`entities: validator failed for field "Competition.display_name": %w`, err)}
		}
	}
	return nil
}

func (cuo *CompetitionUpdateOne) sqlSave(ctx context.Context) (_node *Competition, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(competition.Table, competition.Columns, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeString))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entities: missing "Competition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, competition.FieldID)
		for _, f := range fields {
			if !competition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entities: invalid field %q for query", f)}
			}
			if f != competition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Hidden(); ok {
		_spec.SetField(competition.FieldHidden, field.TypeBool, value)
	}
	if cuo.mutation.HiddenCleared() {
		_spec.ClearField(competition.FieldHidden, field.TypeBool)
	}
	if value, ok := cuo.mutation.Pause(); ok {
		_spec.SetField(competition.FieldPause, field.TypeBool, value)
	}
	if cuo.mutation.PauseCleared() {
		_spec.ClearField(competition.FieldPause, field.TypeBool)
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(competition.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.DisplayName(); ok {
		_spec.SetField(competition.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ViewableToPublic(); ok {
		_spec.SetField(competition.FieldViewableToPublic, field.TypeBool, value)
	}
	if cuo.mutation.ViewableToPublicCleared() {
		_spec.ClearField(competition.FieldViewableToPublic, field.TypeBool)
	}
	if value, ok := cuo.mutation.ToBeStartedAt(); ok {
		_spec.SetField(competition.FieldToBeStartedAt, field.TypeTime, value)
	}
	if cuo.mutation.ToBeStartedAtCleared() {
		_spec.ClearField(competition.FieldToBeStartedAt, field.TypeTime)
	}
	if value, ok := cuo.mutation.StartedAt(); ok {
		_spec.SetField(competition.FieldStartedAt, field.TypeTime, value)
	}
	if cuo.mutation.StartedAtCleared() {
		_spec.ClearField(competition.FieldStartedAt, field.TypeTime)
	}
	if value, ok := cuo.mutation.FinishedAt(); ok {
		_spec.SetField(competition.FieldFinishedAt, field.TypeTime, value)
	}
	if cuo.mutation.FinishedAtCleared() {
		_spec.ClearField(competition.FieldFinishedAt, field.TypeTime)
	}
	if cuo.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.TeamsTable,
			Columns: []string{competition.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !cuo.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.TeamsTable,
			Columns: []string{competition.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.TeamsTable,
			Columns: []string{competition.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ServicesTable,
			Columns: []string{competition.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedServicesIDs(); len(nodes) > 0 && !cuo.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ServicesTable,
			Columns: []string{competition.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ServicesTable,
			Columns: []string{competition.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ReportsTable,
			Columns: []string{competition.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedReportsIDs(); len(nodes) > 0 && !cuo.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ReportsTable,
			Columns: []string{competition.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ReportsTable,
			Columns: []string{competition.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RoundsTable,
			Columns: []string{competition.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedRoundsIDs(); len(nodes) > 0 && !cuo.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RoundsTable,
			Columns: []string{competition.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RoundsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RoundsTable,
			Columns: []string{competition.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(round.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Competition{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{competition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
