protoc .\pkg\proto\utilpb\uuid.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc   
protoc .\pkg\check\checkpb\check.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc 
protoc .\pkg\property\propertypb\property.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc    
protoc .\pkg\round\roundpb\round.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc 
protoc .\pkg\service\servicepb\service.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc   
protoc .\pkg\service_group\service_grouppb\service_group.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc 
protoc .\pkg\host\hostpb\host.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc    
protoc .\pkg\host_group\host_grouppb\host_group.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc  
protoc .\pkg\team\teampb\team.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc    
protoc .\pkg\competition\competitionpb\competition.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc   
protoc .\pkg\report\reportpb\report.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc  
protoc .\pkg\config\configpb\config.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc  
protoc .\pkg\user\userpb\user.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc    
protoc .\pkg\policy\policypb\policy.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc  
protoc .\pkg\auth\auth.proto --js_out=import_style=commonjs,binary:.\web\src\grpc --grpc-web_out=import_style=typescript,mode=grpcwebtext:.\web\src\grpc   