/*
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Check} from './Check';
import {Competition} from './Competition';
import {Host} from './Host';
import {Property} from './Property';
import {Team} from './Team';

/**
 * The Service model module.
 * @module model/Service
 * @version 0.1.0
 */
export class Service {
  /**
   * Constructs a new <code>Service</code>.
   * @alias module:model/Service
   * @class
   * @param id {Number} 
   * @param createTime {Date} 
   * @param updateTime {Date} 
   * @param pause {Boolean} 
   * @param hidden {Boolean} 
   * @param competitionId {Number} 
   * @param teamId {Number} 
   * @param name {String} 
   * @param displayName {String} 
   * @param weight {Number} 
   * @param pointBoost {Number} 
   * @param roundUnits {Number} 
   * @param roundDelay {Number} 
   * @param competition {module:model/Competition} 
   * @param team {module:model/Team} 
   */
  constructor(id, createTime, updateTime, pause, hidden, competitionId, teamId, name, displayName, weight, pointBoost, roundUnits, roundDelay, competition, team) {
    this.id = id;
    this.createTime = createTime;
    this.updateTime = updateTime;
    this.pause = pause;
    this.hidden = hidden;
    this.competitionId = competitionId;
    this.teamId = teamId;
    this.name = name;
    this.displayName = displayName;
    this.weight = weight;
    this.pointBoost = pointBoost;
    this.roundUnits = roundUnits;
    this.roundDelay = roundDelay;
    this.competition = competition;
    this.team = team;
  }

  /**
   * Constructs a <code>Service</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Service} obj Optional instance to populate.
   * @return {module:model/Service} The populated <code>Service</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Service();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('create_time'))
        obj.createTime = ApiClient.convertToType(data['create_time'], 'Date');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'Date');
      if (data.hasOwnProperty('pause'))
        obj.pause = ApiClient.convertToType(data['pause'], 'Boolean');
      if (data.hasOwnProperty('hidden'))
        obj.hidden = ApiClient.convertToType(data['hidden'], 'Boolean');
      if (data.hasOwnProperty('competition_id'))
        obj.competitionId = ApiClient.convertToType(data['competition_id'], 'Number');
      if (data.hasOwnProperty('team_id'))
        obj.teamId = ApiClient.convertToType(data['team_id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('display_name'))
        obj.displayName = ApiClient.convertToType(data['display_name'], 'String');
      if (data.hasOwnProperty('weight'))
        obj.weight = ApiClient.convertToType(data['weight'], 'Number');
      if (data.hasOwnProperty('point_boost'))
        obj.pointBoost = ApiClient.convertToType(data['point_boost'], 'Number');
      if (data.hasOwnProperty('round_units'))
        obj.roundUnits = ApiClient.convertToType(data['round_units'], 'Number');
      if (data.hasOwnProperty('round_delay'))
        obj.roundDelay = ApiClient.convertToType(data['round_delay'], 'Number');
      if (data.hasOwnProperty('competition'))
        obj.competition = Competition.constructFromObject(data['competition']);
      if (data.hasOwnProperty('team'))
        obj.team = Team.constructFromObject(data['team']);
      if (data.hasOwnProperty('hosts'))
        obj.hosts = Host.constructFromObject(data['hosts']);
      if (data.hasOwnProperty('checks'))
        obj.checks = ApiClient.convertToType(data['checks'], [Check]);
      if (data.hasOwnProperty('properties'))
        obj.properties = ApiClient.convertToType(data['properties'], [Property]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Service.prototype.id = undefined;

/**
 * @member {Date} createTime
 */
Service.prototype.createTime = undefined;

/**
 * @member {Date} updateTime
 */
Service.prototype.updateTime = undefined;

/**
 * @member {Boolean} pause
 */
Service.prototype.pause = undefined;

/**
 * @member {Boolean} hidden
 */
Service.prototype.hidden = undefined;

/**
 * @member {Number} competitionId
 */
Service.prototype.competitionId = undefined;

/**
 * @member {Number} teamId
 */
Service.prototype.teamId = undefined;

/**
 * @member {String} name
 */
Service.prototype.name = undefined;

/**
 * @member {String} displayName
 */
Service.prototype.displayName = undefined;

/**
 * @member {Number} weight
 */
Service.prototype.weight = undefined;

/**
 * @member {Number} pointBoost
 */
Service.prototype.pointBoost = undefined;

/**
 * @member {Number} roundUnits
 */
Service.prototype.roundUnits = undefined;

/**
 * @member {Number} roundDelay
 */
Service.prototype.roundDelay = undefined;

/**
 * @member {module:model/Competition} competition
 */
Service.prototype.competition = undefined;

/**
 * @member {module:model/Team} team
 */
Service.prototype.team = undefined;

/**
 * @member {module:model/Host} hosts
 */
Service.prototype.hosts = undefined;

/**
 * @member {Array.<module:model/Check>} checks
 */
Service.prototype.checks = undefined;

/**
 * @member {Array.<module:model/Property>} properties
 */
Service.prototype.properties = undefined;

