/*
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TeamUpdate model module.
 * @module model/TeamUpdate
 * @version 0.1.0
 */
export class TeamUpdate {
  /**
   * Constructs a new <code>TeamUpdate</code>.
   * @alias module:model/TeamUpdate
   * @class
   * @param id {Number} 
   * @param createTime {Date} 
   * @param updateTime {Date} 
   * @param pause {Boolean} 
   * @param hidden {Boolean} 
   * @param competitionId {Number} 
   * @param name {String} 
   * @param index {Number} 
   */
  constructor(id, createTime, updateTime, pause, hidden, competitionId, name, index) {
    this.id = id;
    this.createTime = createTime;
    this.updateTime = updateTime;
    this.pause = pause;
    this.hidden = hidden;
    this.competitionId = competitionId;
    this.name = name;
    this.index = index;
  }

  /**
   * Constructs a <code>TeamUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamUpdate} obj Optional instance to populate.
   * @return {module:model/TeamUpdate} The populated <code>TeamUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamUpdate();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('create_time'))
        obj.createTime = ApiClient.convertToType(data['create_time'], 'Date');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'Date');
      if (data.hasOwnProperty('pause'))
        obj.pause = ApiClient.convertToType(data['pause'], 'Boolean');
      if (data.hasOwnProperty('hidden'))
        obj.hidden = ApiClient.convertToType(data['hidden'], 'Boolean');
      if (data.hasOwnProperty('competition_id'))
        obj.competitionId = ApiClient.convertToType(data['competition_id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('index'))
        obj.index = ApiClient.convertToType(data['index'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
TeamUpdate.prototype.id = undefined;

/**
 * @member {Date} createTime
 */
TeamUpdate.prototype.createTime = undefined;

/**
 * @member {Date} updateTime
 */
TeamUpdate.prototype.updateTime = undefined;

/**
 * @member {Boolean} pause
 */
TeamUpdate.prototype.pause = undefined;

/**
 * @member {Boolean} hidden
 */
TeamUpdate.prototype.hidden = undefined;

/**
 * @member {Number} competitionId
 */
TeamUpdate.prototype.competitionId = undefined;

/**
 * @member {String} name
 */
TeamUpdate.prototype.name = undefined;

/**
 * @member {Number} index
 */
TeamUpdate.prototype.index = undefined;

