/*
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserList model module.
 * @module model/UserList
 * @version 0.1.0
 */
export class UserList {
  /**
   * Constructs a new <code>UserList</code>.
   * @alias module:model/UserList
   * @class
   * @param id {Number} 
   * @param createTime {Date} 
   * @param updateTime {Date} 
   * @param username {String} 
   */
  constructor(id, createTime, updateTime, username) {
    this.id = id;
    this.createTime = createTime;
    this.updateTime = updateTime;
    this.username = username;
  }

  /**
   * Constructs a <code>UserList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserList} obj Optional instance to populate.
   * @return {module:model/UserList} The populated <code>UserList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserList();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('create_time'))
        obj.createTime = ApiClient.convertToType(data['create_time'], 'Date');
      if (data.hasOwnProperty('update_time'))
        obj.updateTime = ApiClient.convertToType(data['update_time'], 'Date');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
UserList.prototype.id = undefined;

/**
 * @member {Date} createTime
 */
UserList.prototype.createTime = undefined;

/**
 * @member {Date} updateTime
 */
UserList.prototype.updateTime = undefined;

/**
 * @member {String} username
 */
UserList.prototype.username = undefined;

