name: Codecov

on:
  push:
    branches:
      - master
      - main

jobs:
  codecov:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
    services:
      cockroachdb:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: scoretrak
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: password

    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Generate coverage report
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./pkg/...
