name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Download golang environment"
        uses: actions/setup-go@v2
      - run: go version
      - run: go mod tidy
      - name: "Download Cockroach DB"
        run: wget -qO- https://binaries.cockroachdb.com/cockroach-v20.1.1.linux-amd64.tgz | tar  xvz
      - name: "Move Cockroach DB to /usr/local/bin/"
        run: sudo cp -i cockroach-v20.1.1.linux-amd64/cockroach /usr/local/bin/
      - name: "Start Cockroach DB in background"
        run: cockroach start-single-node --insecure --background --listen-addr=localhost:26257
      - name: "Start golang test"
        run: go test ./pkg/... --race -coverprofile=coverage.txt -covermode=atomic
        env:
          AUTO_TEST: "TRUE"
      - name: "Code Coverage"
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}