/*
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EntSchemaApi);
  }
}(this, function(expect, EntSchemaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EntSchemaApi.CompetitionApi();
  });

  describe('(package)', function() {
    describe('CompetitionApi', function() {
      describe('createCompetition', function() {
        it('should call createCompetition successfully', function(done) {
          // TODO: uncomment, update parameter values for createCompetition call and complete the assertions
          /*

          instance.createCompetition(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EntSchemaApi.CompetitionCreate);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteCompetition', function() {
        it('should call deleteCompetition successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteCompetition call
          /*

          instance.deleteCompetition(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listCompetition', function() {
        it('should call listCompetition successfully', function(done) {
          // TODO: uncomment, update parameter values for listCompetition call and complete the assertions
          /*
          var opts = {};

          instance.listCompetition(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EntSchemaApi.CompetitionList);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listCompetitionTeams', function() {
        it('should call listCompetitionTeams successfully', function(done) {
          // TODO: uncomment, update parameter values for listCompetitionTeams call and complete the assertions
          /*
          var opts = {};

          instance.listCompetitionTeams(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EntSchemaApi.CompetitionTeamsList);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readCompetition', function() {
        it('should call readCompetition successfully', function(done) {
          // TODO: uncomment, update parameter values for readCompetition call and complete the assertions
          /*

          instance.readCompetition(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EntSchemaApi.CompetitionRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateCompetition', function() {
        it('should call updateCompetition successfully', function(done) {
          // TODO: uncomment, update parameter values for updateCompetition call and complete the assertions
          /*

          instance.updateCompetition(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EntSchemaApi.CompetitionUpdate);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
