/*
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EntSchemaApi);
  }
}(this, function(expect, EntSchemaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EntSchemaApi.RoundApi();
  });

  describe('(package)', function() {
    describe('RoundApi', function() {
      describe('createRound', function() {
        it('should call createRound successfully', function(done) {
          // TODO: uncomment, update parameter values for createRound call and complete the assertions
          /*

          instance.createRound(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EntSchemaApi.RoundCreate);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteRound', function() {
        it('should call deleteRound successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteRound call
          /*

          instance.deleteRound(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listRound', function() {
        it('should call listRound successfully', function(done) {
          // TODO: uncomment, update parameter values for listRound call and complete the assertions
          /*
          var opts = {};

          instance.listRound(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EntSchemaApi.RoundList);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readRound', function() {
        it('should call readRound successfully', function(done) {
          // TODO: uncomment, update parameter values for readRound call and complete the assertions
          /*

          instance.readRound(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EntSchemaApi.RoundRead);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateRound', function() {
        it('should call updateRound successfully', function(done) {
          // TODO: uncomment, update parameter values for updateRound call and complete the assertions
          /*

          instance.updateRound(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EntSchemaApi.RoundUpdate);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
